CRITICAL - 2021-09-21 11:50:37 --> ini_set(): Headers already sent. You cannot change the session module's ini settings at this time
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'ini_set(): Head...', 'C:\\WORKSPACE\\eG...', 80, Array)
#1 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Session\Handlers\FileHandler.php(80): ini_set('session.save_pa...', 'C:\\WORKSPACE\\eG...')
#2 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Config\Services.php(706): CodeIgniter\Session\Handlers\FileHandler->__construct(Object(Config\App), '::1')
#3 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Config\BaseService.php(100): CodeIgniter\Config\Services::session(Object(Config\App), false)
#4 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Config\Services.php(699): CodeIgniter\Config\BaseService::getSharedInstance('session', NULL)
#5 C:\WORKSPACE\eGateway_py\gui\app\Controllers\BaseController.php(38): CodeIgniter\Config\Services::session()
#6 C:\WORKSPACE\eGateway_py\gui\app\Controllers\Backup.php(13): App\Controllers\BaseController->__construct()
#7 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(907): App\Controllers\Backup->__construct()
#8 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(421): CodeIgniter\CodeIgniter->createController()
#9 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\CodeIgniter.php(332): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#10 C:\WORKSPACE\eGateway_py\gui\public\index.php(45): CodeIgniter\CodeIgniter->run()
#11 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Commands\Server\rewrite.php(45): require_once('C:\\WORKSPACE\\eG...')
#12 {main}
CRITICAL - 2021-09-21 11:50:37 --> Uncaught ErrorException: Cannot modify header information - headers already sent by (output started at C:\WORKSPACE\eGateway_py\gui\app\Config\Events.php:27) in C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Debug\Exceptions.php:137
Stack trace:
#0 [internal function]: CodeIgniter\Debug\Exceptions->errorHandler(2, 'Cannot modify h...', 'C:\\WORKSPACE\\eG...', 137, Array)
#1 C:\WORKSPACE\eGateway_py\gui\vendor\codeigniter4\framework\system\Debug\Exceptions.php(137): header('HTTP/1.1 500 In...', true, 500)
#2 [internal function]: CodeIgniter\Debug\Exceptions->exceptionHandler(Object(ErrorException))
#3 {main}
  thrown
#0 [internal function]: CodeIgniter\Debug\Exceptions->shutdownHandler()
#1 {main}
